##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#############################################################################################
# This role deletes the Vault configurations
#############################################################################################

# Delete the Docker credentials
- name: Delete docker creds
  k8s:
    kind: Secret
    namespace: "{{ org_namespace }}"
    name: "regcred"
    state: absent
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
  ignore_errors: yes

# Delete Ambassador credentials
- name: Delete Ambassador creds
  k8s:
    kind: Secret
    namespace: "{{ org_namespace }}"
    name: "{{ peer.name }}-ambassador-certs"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    state: absent
  loop: "{{ services.peers }}"
  loop_control:
    loop_var: peer
  ignore_errors: yes

# Delete Peer Crypto material (including IPFS keys if applicable)
- name: Delete Peer Crypto material
  shell: |
    {% if peer.type == "member" %}
      {% if peer.ipfs is defined %}
        vault kv delete {{ item.vault.secret_path | default('secretsv2') }}/{{ network.env.type }}{{ org_name }}/substrate-node-{{ peer.name }}-ipfs-keys
      {% endif %}
    {% endif %}
    vault kv delete {{ item.vault.secret_path | default('secretsv2') }}/{{ network.env.type }}{{ org_name }}/substrate-node-{{ peer.name }}-keys
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"
  loop: "{{ services.peers }}"
  loop_control:
    loop_var: peer
  ignore_errors: yes

# Delete Genesis and Ambassador crypto material
- name: Delete genesis & ambassador crypto material
  shell: |
    vault kv delete {{ item.vault.secret_path | default('secretsv2') }}/{{ network.env.type }}{{ org_name }}/tlscerts
    vault kv delete {{ item.vault.secret_path | default('secretsv2') }}/{{ network.env.type }}{{ org_name }}/genesis
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"
  ignore_errors: yes
