apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ccquorum
  namespace: c-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: ccquorum
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-member-node
    sourceRef:
      kind: GitRepository
      name: flux-quodlt
      namespace: flux-quodlt
  values:
    replicaCount: 1
    metadata:
      namespace: c-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    node:
      name: c
      status: default
      consensus: ibft
      subject: O=c,OU=c,L=51.50/-0.13/London,C=GB
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        quorum: 21000

    tm:
      type: tessera

    vault:
      type: hashicorp
      address: http://dev-vault-public.dev.aws.blockchaincloudpoc-develop.com
      secretprefix: secretsv2/data/c/crypto/c
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: tm
      role: vault-role
      authpath: quodltc
      
    tessera:
      url: "https://c.sau99.dev.aws.blockchaincloudpoc-develop.com:443"
      clienturl: "http://c-tessera:8888" #TODO: Enable tls strict for q2t
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjVhZjY4NTgiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg2ZmVhOTQ0NDFhZWQzOGEwOWQ0OTI2NGU1MDY3NTY1YzUzN2NmN2NhNDA2ZjNkOTRkOTg0MzliNmEyMmM5OGEyODdiOTliMWViYjE5ZjQwNjc2YTMzN2E3Yjg0MTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBjMCIsCiAgImdhc0xpbWl0IjogIjB4ZTAwMDAwMDAiLAogICJkaWZmaWN1bHR5IjogIjB4MSIsCiAgIm1peEhhc2giOiAiMHg2Mzc0Njk2MzYxNmMyMDYyNzk3YTYxNmU3NDY5NmU2NTIwNjY2MTc1NmM3NDIwNzQ2ZjZjNjU3MjYxNmU2MzY1IiwKICAiY29pbmJhc2UiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAiYWxsb2MiOiB7CiAgICAiNDQxYWVkMzhhMDlkNDkyNjRlNTA2NzU2NWM1MzdjZjdjYTQwNmYzZCI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgImQ5ODQzOWI2YTIyYzk4YTI4N2I5OWIxZWJiMTlmNDA2NzZhMzM3YTciOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfQogIH0sCiAgIm51bWJlciI6ICIweDAiLAogICJnYXNVc2VkIjogIjB4MCIsCiAgInBhcmVudEhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgp9
    staticnodes:
      [
    "enode://c587912fae5e28d5e2a2ec170012dd9616b8b0d45b098bd8cf9af697bf43b9c7d9a5f724a7f8bd983a5d152885bcecb547ac0bc022ff3fbdda8f07c7c03b04aa@c.sau99.dev.aws.blockchaincloudpoc-develop.com:15010?discport=0",
    "enode://ef83219ee3d91d912ee879bea0f92266de27e9867e21f6b0b7529dbeaae1c5a588511a14e24f2d462d64bd68cee7cf65a5c908ac4ad560677e7a466f25971ff1@v1.sau99.dev.aws.blockchaincloudpoc-develop.com:15014?discport=0",
    "enode://997b1518fbc18358e435d6a71e60b15527bc180a80b05a4fa654cb4ead20a59a3d250324d48ac65b17f60ec461ce1e593d8ecd249155ded086a79c5b965efa8c@m.sau99.dev.aws.blockchaincloudpoc-develop.com:15020?discport=0",
    "enode://a4c3feb86db4a150d224ae42b00ccef7916dea4345f80336f1b35e45c0f113db0aa1a55a0cb9f276ae3344c9918c5a10a248fcfb5ef889d1e59963b931db8df3@v2.sau99.dev.aws.blockchaincloudpoc-develop.com:15024?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: sau99.dev.aws.blockchaincloudpoc-develop.com
      quorumport: 15010
    storage:
      storageclassname: c-bevel-storageclass
      storagesize: 1Gi
      dbstorage: 1Gi
