apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cv1quorum
  namespace: c-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: cv1quorum
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-validator-node
    sourceRef:
      kind: GitRepository
      name: flux-quodlt
      namespace: flux-quodlt
  values:
    nameOverride: v1
    replicaCount: 1
    global:
      vault:
        type: hashicorp
        address: http://dev-vault-public.dev.aws.blockchaincloudpoc-develop.com
        role: vault-role
        authPath: quodltc
        serviceAccountName: vault-auth
        secretPrefix: secretsv2/data/c/crypto/v1
        keyName: quorum
    metadata:
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    node:
      name: v1
      status: default
      consensus: ibft
      subject: O=v1,OU=v1,L=51.50/-0.13/London,C=GB
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keyStore: keystore_1
      serviceType: ClusterIP
      lock: false
      ports:
        rpc: 8546
        quorum: 21000
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjViNzU2M2UiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg2ZmVhOTRkYzc0NDNjOGVhY2UxMDk4OGE1NDZlZWJmYmFiZTUwMmExZTJlODE4OTRmZGU2OThiYzA3YjcyYTk0ZjRjYTAzMWQ3NWQxNDFjOWYxYmYwMDY0Yjg0MTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBjMCIsCiAgImdhc0xpbWl0IjogIjB4ZTAwMDAwMDAiLAogICJkaWZmaWN1bHR5IjogIjB4MSIsCiAgIm1peEhhc2giOiAiMHg2Mzc0Njk2MzYxNmMyMDYyNzk3YTYxNmU3NDY5NmU2NTIwNjY2MTc1NmM3NDIwNzQ2ZjZjNjU3MjYxNmU2MzY1IiwKICAiY29pbmJhc2UiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAiYWxsb2MiOiB7CiAgICAiZGM3NDQzYzhlYWNlMTA5ODhhNTQ2ZWViZmJhYmU1MDJhMWUyZTgxOCI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgImZkZTY5OGJjMDdiNzJhOTRmNGNhMDMxZDc1ZDE0MWM5ZjFiZjAwNjQiOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfQogIH0sCiAgIm51bWJlciI6ICIweDAiLAogICJnYXNVc2VkIjogIjB4MCIsCiAgInBhcmVudEhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgp9
    staticnodes: [
    "enode://87d6f68161491d732807e2ac3a4d3700303febe095730dc0d7a5c1bedbe95467f21ea4976fcc6ad1efd4481d961dc2cd826044eda58025cfc4cb0ee939f86286@c.sau99.dev.aws.blockchaincloudpoc-develop.com:15010?discport=0",
    "enode://d748e8b630dfa5f02ced43a0abb94f91fd6bdc618ba5152a7f5fe425da61b39be777460d92f3b41104d0297f7ab3861a5ced449ec2a21bbb397d480f6e335d37@v1.sau99.dev.aws.blockchaincloudpoc-develop.com:15014?discport=0",
    "enode://e61a17077d5a602f5a67cb0a0a0e7b7739a424c7f2cd7215899af800f9ef2f9e8d2217ada36406beeed8b57774b4b0785c519f54e5f3e832fe0791af4c731050@m.sau99.dev.aws.blockchaincloudpoc-develop.com:15020?discport=0",
    "enode://af4f1ff92fbc053254b9b80efc7486b2d830ec4a82484f79c7b2ca51d5a126f17dbfe59b15e51d3c7cdeb30fa5c62b7c194f07e88e1cdcd1e88ca88b7fd7b9b9@v2.sau99.dev.aws.blockchaincloudpoc-develop.com:15024?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: sau99.dev.aws.blockchaincloudpoc-develop.com
      quorumPort: 15014
    storage:
      storageClassName: c-bevel-storageclass
      storageSize: 1Gi
    settings:
      removeGenesisOnDelete: true
    labels:
