##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: fabric
    app.kubernetes.io/part-of: {{ include "fabric-ca-server.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- include "labels.service" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ include "fabric-ca-server.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
  ports:
  - name: tcp
    protocol: TCP
    targetPort: 7054
    port: {{ .Values.server.clusterIpPort }}
    {{- if .Values.server.nodePort }}
    nodePort: {{ .Values.server.nodePort }}
    {{- end }}
  - name: operations
    protocol: TCP
    targetPort: 9443
    port: 9443

{{- if eq .Values.global.proxy.provider "haproxy" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace:  {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: "haproxy"
  rules:
  - host: ca.{{ .Release.Namespace }}.{{ .Values.global.proxy.externalUrlSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ca
            port:
              number: {{ .Values.server.clusterIpPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ops
  namespace:  {{ .Release.Namespace }}
spec:
  ingressClassName: "haproxy"
  rules:
  - host: ca-ops.{{ .Release.Namespace }}.{{ .Values.global.proxy.externalUrlSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ca
            port:
              number: 9443
{{- end }}
