apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: partner-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-dtg
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-domain-genesis
    sourceRef:
      kind: GitRepository
      name: flux-main-indy
      namespace: flux-main-indy
  values:
    metadata:
      name: partner-dtg
      namespace: partner-ns
    organization:
      name: partner
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"3cp2iKYyAYr92zYHwRMQjz","role":"0","verkey":"2Rk3LoQZZvC2UfYFVkU96J5qHPg7DcKDeidAxX32s4NT"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-trustee","dest":"3PF9tnsHFm3BMs1JYz37Ge","role":"0","verkey":"2JMAdkDGFbaiWyGe79u4R2ob1RrdTqzq8WFv6inRutSh"},"metadata":{"from":"3cp2iKYyAYr92zYHwRMQjz"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-1","dest":"BB7YbaYARxKwsKBPmavnCE","role":"2","verkey":"6YddZ7Y8ViLJQWQnv43n8VvT5SneiRcZD2HzDeZ6Uo2o"},"metadata":{"from":"3PF9tnsHFm3BMs1JYz37Ge"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-2","dest":"4tR9jYrVrPZpDVc5X2pYGm","role":"2","verkey":"37rrg6QYQUCGuLbY9TZSxXKFJ365zLEZmm3hnmSDuTgD"},"metadata":{"from":"3PF9tnsHFm3BMs1JYz37Ge"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-trustee","dest":"UdCoPM5wLi9GM17wuaLtJ2","role":"0","verkey":"G4FowuMCgshXCoaWt2ut4xfKhL17QTEDyjwNnwLQHXEz"},"metadata":{"from":"3cp2iKYyAYr92zYHwRMQjz"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-1","dest":"GDbt4zzcMSbT2fM7CwjaTt","role":"2","verkey":"9J3megFnWL9J3MAUc44dMwRtc2rzo9yQuhMEd528KyD8"},"metadata":{"from":"UdCoPM5wLi9GM17wuaLtJ2"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-2","dest":"WgVQwZnPpAf8aWzPQPYjy5","role":"2","verkey":"HBGgwjHN2zPmEK4AAdjBzwrh5QJ3seJNKfHvz1xuBw21"},"metadata":{"from":"UdCoPM5wLi9GM17wuaLtJ2"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
