apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: partner-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-dtg
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-domain-genesis
    sourceRef:
      kind: GitRepository
      name: flux-main-indy
      namespace: flux-main-indy
  values:
    metadata:
      name: partner-dtg
      namespace: partner-ns
    organization:
      name: partner
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"SXb2GHPgLUt66PhrMrLcYu","role":"0","verkey":"EuyG7vzYC28fYQDcxW8ug9HMC5KagDRJH7Ae3qSnSVZi"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-trustee","dest":"HhpiHusMyHn5zQ5QF4y8WY","role":"0","verkey":"A73PnnsLjicH3o5bWdakjVHMxfmGWfbn84PMSFyvHktd"},"metadata":{"from":"SXb2GHPgLUt66PhrMrLcYu"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-1","dest":"6fNxyx31uxEpXBTjYDEWzD","role":"2","verkey":"45yhWQq3W7jaTW8sqYfYZvjinHivzxStV3pNd7CBWmkp"},"metadata":{"from":"HhpiHusMyHn5zQ5QF4y8WY"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-2","dest":"4BLzXWu4372a2C5yrs6YaD","role":"2","verkey":"2jUVwWTCoYQxNHW227Hrw6AtxNdEWHP2y7hFSVQg9gAM"},"metadata":{"from":"HhpiHusMyHn5zQ5QF4y8WY"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-trustee","dest":"9ex9CJuVUhs6PNHhjojAQm","role":"0","verkey":"5iaennwdjmWQqcvZa1ngWedCTPot6C9rzpp5z3E7WBmS"},"metadata":{"from":"SXb2GHPgLUt66PhrMrLcYu"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-1","dest":"LP2B6ujz1wCENuwTMQMmuy","role":"2","verkey":"BZdVksnbKT2YfiTSFarQCMX7zE6mG7XJVARJnSChwf6m"},"metadata":{"from":"9ex9CJuVUhs6PNHhjojAQm"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-2","dest":"TTCWuFXASTTsW2sFBVNEWk","role":"2","verkey":"FRC3M7uoKS9VXvUnsXA1MXyDR4qEZaf5yAKwAa4iU4DE"},"metadata":{"from":"9ex9CJuVUhs6PNHhjojAQm"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
