apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: provider-provider-endorser-transaction
  annotations:
    fluxcd.io/automated: "false"
  namespace: provider-ns
spec:
  releaseName: provider-provider-endorser-transaction
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-ledger-txn
    sourceRef:
      kind: GitRepository
      name: flux-main-indy
      namespace: flux-main-indy
  values:
    metadata:
      name: provider-provider-endorser-transaction
      namespace: provider-ns
    network:
      name: bevel
    image:
      cli:
        name: provider
        repository: ghcr.io/hyperledger/bevel-indy-ledger-txn:latest
        pullSecret: regcred
        pullPolicy: IfNotPresent
    vault:
      address: http://98.64.226.131:20001
      role: rw
      serviceAccountName: provider-admin-vault-auth
      auth_path: kubernetes-provider-admin-auth
    organization:
      name: provider
      adminIdentity:
        name: authority-trustee
        did: 3zBxv8wZ5xVe1GaPmtsRCU
        path: authority/data/trustees
      newIdentity:
        name: provider-endorser
        role: ENDORSER
        did: TeHgG7BnU9Z9NLuLhVcM1P
        verkey: FXEawrbojYbuUgTDZ6kVDfapUxqxMyiNL7JTjz9dYtWd
        path: provider/data/endorsers
    node:
      name: provider
