##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Generate member node helmrelease file
- name: Create value file for member nodes
  include_role:
    name: create/helm_component
  vars:
    component_name: "{{ peer.name }}"
    type: "node_substrate"
    storageclass_name: "{{ item.name | lower }}-bevel-storageclass"
    external_url: "{{ item.external_url_suffix }}"
    vault: "{{ item.vault }}"
    git_url: "{{ item.gitops.git_url }}"
    git_branch: "{{ item.gitops.branch }}"
    org: "{{ item }}"
    docker_url: "{{ network.docker.url }}"
    charts_dir: "{{ item.gitops.chart_source }}"
    values_dir: "{{playbook_dir}}/../../../{{item.gitops.release_dir}}/{{ item.name | lower }}"    
    bootnode_data: "{{ lookup('file', '{{ network.config.bootnodes }}').splitlines() }}"
    command: "{{ network.config.command }}"
    role: "full"
    isBootnode: true

# Git Push : Push the above generated files to git directory 
- name: Git Push
  include_role: 
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    gitops: "{{ item.gitops }}"
    msg: "[ci skip] Pushing Peer files"

# Check if ipfs-bootnode is running
- name: Check if {{ peer.name }} is running
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_name: "{{ peer.name }}"
    component_type: Pod
    label_selectors:
      - name = {{ component_name }}
    namespace: "{{ component_ns }}"
  tags: notest
