apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: member-1-ipfs-node
  namespace: supplychain-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: member-1-ipfs-node
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-substrate
        namespace: flux-substrate
      chart: platforms/substrate/charts/dscp-ipfs-node
  values:
    global:
        serviceAccountName: vault-auth
        vault:
          type: hashicorp
          role: vault-role
          network: substrate
          address: http://98.64.226.131:20001
          authPath: substrate
          secretEngine: secretsv2
          secretPrefix: "data/substrate/supplychain/substrate-node-member-1"
    fullnameOverride: member-1-ipfs
    namespace: supplychain-subs
    config:
      healthCheckPort: 80
      healthCheckPollPeriod: 30000
      healthCheckTimeout: 2000
      nodeHost: "member-1"
      nodePort: "9944"
      logLevel: info
      ipfsApiPort: 5001
      ipfsSwarmPort: 4001
      ipfsDataPath: "/ipfs"
      ipfsCommand: "/usr/local/bin/ipfs"
      ipfsArgs:
        - daemon
        - "--migrate"
      ipfsSwarmAddrFilters: null
      ipfsLogLevel: info
      ipfsBootNodeAddress: /dns4/member-1-ipfs-swarm.supplychain-subs.svc.cluster.local/tcp/4001/p2p/12D3KooWDcFZBzLxWHtKuZQBwSzbZFjCCPHCcesW3JZC8PqUcFdc
      
    service:
      swarm:
        annotations: {}
        enabled: true
        port: 4001
      api:
        annotations: {}
        enabled: true
        port: 5001

    statefulSet:
      annotations: {}
      livenessProbe:
        enabled: true
    image:
      repository: ghcr.io/inteli-poc/dscp-ipfs
      pullPolicy: IfNotPresent
      tag: 'v2.6.2'
    storage:
      storageClass: "supplychain-bevel-storageclass"
      dataVolumeSize: 20  # in Gigabytes
    dscpNode:
      enabled: false
    proxy:
      provider: ambassador
      external_url: member-1-ipfs-swarm.sub.blockchaincloudpoc-develop.com
      port: 15061
      certSecret: supplychain-ambassador-certs
