---
# helm install supplychain -f values/noproxy-and-novault/network-service.yaml -n supplychain-ns corda-network-service
# helm upgrade supplychain -f values/noproxy-and-novault/network-service.yaml -n supplychain-ns corda-network-service
global:
  serviceAccountName: vault-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://98.64.226.131:20001
    authPath: test
    secretEngine: secretsv2
    secretPrefix: "data/test"
    network: corda-enterprise
  proxy:
    provider: "ambassador"
    externalUrlSuffix: corda.blockchaincloudpoc-develop.com
storage:
  size: 1Gi
  dbSize: 5Gi
  allowedTopologies:
    enabled: false

settings:
  removeKeysOnDelete: true # this will erase keys

tls:
  enabled: true
  settings:
    networkServices: true
