---
#helm install notary -f values/noproxy-and-novault/notary.yaml -n supplychain-ns corda-node 
#helm upgrade notary -f values/noproxy-and-novault/notary.yaml -n supplychain-ns corda-node
global:
  serviceAccountName: vault-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://98.64.226.131:20001
    authPath: test
    secretEngine: secretsv2
    secretPrefix: "data/test"
  proxy:
    provider: "ambassador"
    externalUrlSuffix: corda.blockchaincloudpoc-develop.com
image:
  notary:
    repository: corda/corda-enterprise
    tag: 4.10.3-zulu-openjdk8-alpine

network:
  creds:
    truststore: password

tls:
  nameOverride: notary   # should match the release name
  enabled: true

nodeConf:
  legalName: "O=Notary,OU=Notary,L=London,C=GB"
  notary:
    validating: true
    serviceLegalName: "O=Notary,OU=Notary Service,L=London,C=GB"
  doormanPort: 443
  networkMapPort: 443
  doormanDomain: cenm-doorman.corda.blockchaincloudpoc-develop.com
  networkMapDomain: cenm-nms.corda.blockchaincloudpoc-develop.com
  networkMapURL: https://cenm-nms.corda.blockchaincloudpoc-develop.com
  doormanURL: https://cenm-doorman.corda.blockchaincloudpoc-develop.com
