apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: c-generate-ambassador-certs-job
  namespace: c-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: c-generate-ambassador-certs-job
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-tlscerts-gen
    sourceRef:
      kind: GitRepository
      name: flux-quo-dlt
      namespace: flux-quo-dlt
  values:
    nameOverride: c
    global:
      vault:
        type: hashicorp
        address: http://dev-vault-public.dev.aws.blockchaincloudpoc-develop.com
        role: vault-role
        authPath: quo-dltc
        serviceAccountName: vault-auth
        secretPrefix: secretsv2/data/c
    name: "c"
    image:
      initContainerName: ghcr.io/hyperledger/bevel-alpine:latest
      certsContainerName: ghcr.io/hyperledger/bevel-build:jdk8-latest
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
    subjects:
      root_subject: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
      cert_subject: "CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB"
    opensslVars:
      domain_name: "c.sau99.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_api: "capi.sau99.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_web: "cweb.sau99.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_tessera: "c-tessera.c-quo"
      clientPort: 8888
    settings:
      removeGenesisOnDelete: true
    label:
