##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Increment the validator_count for each peer that is a 'bootnode' or 'validator'
- name: Count validator nodes
  set_fact:
    validator_count: "{{ validator_count | int + 1 }}"
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer
  when: peer.type == 'bootnode' or peer.type == 'validator'

# Increment the member_count for each peer that is a 'member'
- name: Count member nodes
  set_fact:
    member_count: "{{ member_count | int  + 1 }}"
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer
  when: peer.type == 'member'
