##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# - name: Initialize counts
#   set_fact:
#     validator_count: 0
#     member_count: 0

- name: Count validator nodes
  set_fact:
    validator_count: "{{ validator_count | int + 1 }}"
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer
  when: peer.type == 'bootnode' or peer.type == 'validator'

- name: Count member nodes
  set_fact:
    member_count: "{{ member_count | int  + 1 }}"
  loop: "{{ peers }}"
  loop_control:
    loop_var: peer
  when: peer.type == 'member'

- name: Debug counts
  debug:
    msg: "Validator count: {{ validator_count }}, Member count: {{ member_count }}"
