# apiVersion: v2
apiVersion: v1
name: gen_node_chart
description: "Quorum: Deploys genesis node."
type: application
version: 1.0.0
appVersion: latest
keywords:
  - bevel
  - ethereum
  - quorum
  - hyperledger
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
