apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: member-1-ipfs-node
  namespace: oem-subs
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: member-1-ipfs-node
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-s
        namespace: flux-s
      chart: platforms/substrate/charts/dscp-ipfs-node
  values:
    fullnameOverride: member-1-ipfs
    namespace: oem-subs
    config:
      healthCheckPort: 80
      healthCheckPollPeriod: 30000
      healthCheckTimeout: 2000
      nodeHost: "tierone"
      nodePort: "9944"
      logLevel: info
      ipfsApiPort: 5001
      ipfsSwarmPort: 4001
      ipfsDataPath: "/ipfs"
      ipfsCommand: "/usr/local/bin/ipfs"
      ipfsArgs:
        - daemon
        - "--migrate"
      ipfsSwarmAddrFilters: null
      ipfsLogLevel: info
      ipfsBootNodeAddress: member-1-ipfs-swarm.sub.blockchaincloudpoc-develop.com:15058
    service:
      swarm:
        annotations: {}
        enabled: true
        port: 4001
      api:
        annotations: {}
        enabled: true
        port: 5001

    statefulSet:
      annotations: {}
      livenessProbe:
        enabled: true
    image:
      repository: ghcr.io/inteli-poc/dscp-ipfs
      pullPolicy: IfNotPresent
      tag: 'v2.6.2'
    storage:
      storageClass: "oem-bevel-storageclass"
      dataVolumeSize: 20  # in Gigabytes
    dscpNode:
      enabled: false
    proxy:
      provider: ambassador
      external_url: member-1-ipfs-swarm.sub.blockchaincloudpoc-develop.com
      port: 15059
      certSecret: oem-ambassador-certs
    vault:
      address: http://98.64.226.131:20001
      role: vault-role
      authpath: soem
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/data/oem/member-1
