apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supplychains-notary
  namespace: supplychains-ent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychains-notary
  interval: 1m
  chart:
   spec:
    chart: platforms/r3-corda-ent/charts/enterprise-node
    sourceRef:
      kind: GitRepository
      name: flux-ent-1
      namespace: flux-ent-1
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: "azure"
        cloudNativeServices: false
        kubernetesUrl: "https://devcluster-devresourcegroup-d1d33f-kncld871.hcp.westeurope.azmk8s.io:443"
      vault:
        type: hashicorp
        role: vault-role
        network: corda-enterprise
        address: "http://98.64.226.131:20001"
        authPath: "supplychains"
        secretEngine: secretsv2
        secretPrefix: "data/supplychains"
      proxy:
        provider: ambassador
    image:
      notary:
        repository: corda/corda-enterprise
        tag: 4.10.3-zulu-openjdk8-alpine
    network:
      creds:
        truststore: password
    tls:
      nameOverride: notary-1   # should match the release name
      enabled: true
    sleepTimeAfterError: 180
    storage:
      size: 1Gi
      dbSize: 5Gi
      allowedTopologies:
        enabled: false
    baseDir: /opt/corda
    dataSourceProperties:
      dataSource:
        user: node-db-user
        password: node-db-password
        url: "jdbc:h2:file:./h2/node-persistence;DB_CLOSE_ON_EXIT=FALSE;WRITE_DELAY=0;LOCK_TIMEOUT=10000"
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    nodeConf:
      legalName: O=Notary,OU=Notary,L=London,C=GB
      devMode: false
      creds:
        truststore: cordacadevpass
        keystore: trustpass
      crlCheckSoftFail: true
      tlsCertCrlDistPoint: ""
      tlsCertCrlIssuer: ""
      monitoring:
        enabled: true
        port: 8090
      allowDevCorDapps:
        enabled: true
      p2pPort: 10002
      rpc:
        port: 10003
        adminPort: 10005
        users:
        - name: node
          password: nodeP
          permissions: ALL
      ssh:
        enabled: true
        sshdPort: 2222
      removeKeysOnDelete: false
      firewall:
        enabled: false
      notary:
        serviceLegalName: O=Notary Service,OU=Notary,L=London,C=GB
        validating: True
      doormanPort: 443
      networkMapPort: 443
      doormanDomain: cenm-doorman.sub.blockchaincloudpoc-develop.com
      networkMapDomain: cenm-nms.sub.blockchaincloudpoc-develop.com
      networkMapURL: https://cenm-nms.sub.blockchaincloudpoc-develop.com
      doormanURL: https://cenm-doorman.sub.blockchaincloudpoc-develop.com
    cordapps:
      getcordapps: true
      jars:
        - url: https://maven.pkg.github.com/hyperledger/bevel/com.supplychain.bcc.cordapp-supply-chain/4.9/cordapp-supply-chain-4.9.jar
        - url: https://maven.pkg.github.com/hyperledger/bevel/com.supplychain.bcc.cordapp-contracts-states/4.9/cordapp-contracts-states-4.9.jar
