##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
---
global:
  serviceAccountName: vault-auth
  vault:
    type: hashicorp
    network: substrate
    address: http://vault.demo.com:8200
    authPath: supplychain
    secretEngine: secretsv2
    certPrefix: "subs"
    secretPrefix: "data/supplychain"
    role: vault-role
  cluster:
    provider: azure
    cloudNativeServices: false
    kubernetesUrl: https://kubernetes.url
node:
  validator:
      count: 4
  member:
    count: 1
    balance: 1152921504606846976

