##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
---
global:
  serviceAccountName: vault-auth
  vault:
    type: "hashicorp"
    network: substrate
    address: "http://inteli-vault.stage.intelipoc.com" # http://vault.demo.com:8200
    authPath: tierone # tierone # oem
    secretEngine: secretsv4
    secretPrefix: "data/tierone" # "data/oem" 
    role: vault-role
proxy:
  provider: ambassador 
