apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: "university-steward-4"
  annotations:
    fluxcd.io/automated: "false"
  namespace: "university-indy"
spec:
  releaseName: "university-steward-4"
  interval: 1m
  chart:
    spec:
      interval: 1m
      chart: "platforms/hyperledger-indy/charts/indy-node"
      sourceRef:
        kind: GitRepository
        name: flux-indy
        namespace: flux-indy
  values:
    global:
      serviceAccountName: vault-auth
      cluster:
        provider: "azure"
        cloudNativeServices: false
      proxy:
        provider: ambassador
    
    storage:
      keys: "512Mi"
      data: "4Gi"
    
    image:
      indyNode:
        repository: ghcr.io/hyperledger/bevel-indy-node
        tag: 1.12.6
    
    settings:
      serviceType: ClusterIP
      node:
        publicIp: "ambassador-public-ip"
        port: "9721"
        externalPort: "9721"
      client:
        publicIp: "ambassador-public-ip"
        port: "9722"
        externalPort: "9722"
