##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

dlt_templates:
  generate-keys: generate_keys.tpl
  generate-genesis: generate_genesis.tpl
  stewards: stewards.tpl
