##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cli-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "labels.pvc" . | nindent 4 }}
spec:
  storageClassName: storage-{{ .Release.Name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
