dependencies:
  - name: bevel-storageclass
    alias: storage-test # storage (OLD) # storage-test (NEW)
    repository: "file://../../../shared/charts/bevel-storageclass"
    tags:
      - storage
    version: ~1.0.0
  - name: cenm-auth
    alias: auth
    repository: "file://../cenm-auth"
    tags:
      - cenm
    version: ~1.0.0
  - name: cenm-gateway
    alias: gateway
    repository: "file://../cenm-gateway"
    tags:
      - cenm
    version: ~1.0.0
  - name: cenm-zone
    alias: zone
    repository: "file://../cenm-zone"
    tags:
      - cenm
    version: ~1.0.0
  - name: cenm-signer
    alias: signer
    repository: "file://../cenm-signer"
    tags:
      - bevel
    version: ~1.0.0
  - name: cenm-idman
    alias: idman
    repository: "file://../cenm-idman"
    tags:
      - bevel
    version: ~1.0.0
  - name: corda-certs-gen
    alias: tls
    repository: "file://../../../r3-corda/charts/corda-certs-gen"
    tags:
      - bevel
    version: ~1.0.0
    condition: tls.enabled
