# helm install genesis -f values/noproxy-and-novault/genesis.yaml -n supplychain-quo quorum-genesis
global:
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: kubernetes # kubernetes | aws-secrets-manager
settings:
  removeGenesisOnDelete: true
