# helm install genesis -f values/noproxy-and-novault/genesis-sec.yaml -n carrier-quo quorum-genesis
global:
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: kubernetes # kubernetes | aws-secrets-manager
    secretManagerRegion: 

settings:
  removeGenesisOnDelete: true
  secondaryGenesis: true
