---
#helm install member-2 -f values/noproxy-and-novault/txnode-sec.yml -n carrier-bes besu-node
global:
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: kubernetes
  proxy:
    provider: none
    externalUrlSuffix: svc.cluster.local

tessera:
  enabled: true
  tessera:
    tlsMode: "OFF" # SKK - Shoul be OFF only bcoz STRICT needs TLS configuration means proxy (Ambassador) but we want noproxy here so OFF is suitable here.
    peerNodes: 
      - url: "http://goquorum-tessera-node-member-0.genesis:9000" # "http://tessera-member-1.supplychain-bes:9000"
  resources:
    cpuLimit: 0.25
    cpuRequest: 0.05
    memLimit: "2G"
    memRequest: "1G"
    password: 'password'
  storage:
    enabled: false
    size: 1Gi
    dbSize: 2Gi
    allowedTopologies:
      enabled: false

tls:
  enabled: false
  # settings:
  #   certSubject: CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB
  #   tmTls: true

node:
  goquorum:
    metrics:
      serviceMonitorEnabled: true
    resources:
      cpuLimit: 0.25
      cpuRequest: 0.05
      memLimit: "1G"
      memRequest: "300M"
    account:
      password: 'password'
