global:
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false # set to true to use Cloud Native Services (SecretsManager and IAM for AWS; KeyVault & Managed Identities for Azure)
  vault:
    type: kubernetes

  proxy:
    provider: none
    externalUrlSuffix: svc.cluster.local
