##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

job_templates:
  primary_genesis: primary_genesis.tpl
  secondary_genesis: secondary_genesis.tpl
  primary_init: primary_init.tpl
  secondary_init: secondary_init.tpl
  indy_genesis: indy_genesis.tpl
charts:
  primary_genesis: besu-genesis
  secondary_genesis: besu-genesis
  primary_init: corda-init
  secondary_init: corda-init
  indy_genesis: indy-genesis
