##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

job_templates:
  primary_genesis: primary_genesis.tpl
  secondary_genesis: secondary_genesis.tpl
  primary_init: primary_init.tpl
  secondary_init: secondary_init.tpl
  indy_genesis: indy_genesis.tpl
  indy_endorser: indy_endorser.tpl
  corda_ent_init: corda_ent_init.tpl
  corda_ent_cenm: corda_ent_cenm.tpl
charts:
  primary_genesis: "{{ network.type }}-genesis"
  secondary_genesis: "{{ network.type }}-genesis"
  primary_init: corda-init
  secondary_init: corda-init
  indy_genesis: indy-genesis
  indy_endorser: indy-register-identity
  corda_ent_init: enterprise-init
  corda_ent_cenm: cenm
