global:
  version: 2.2.2
  serviceAccountName: vault-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.url:8200
    authPath: carrier
    secretEngine: secretsv2
    secretPrefix: "data/carrier"
    tls: false
  proxy:
    provider: haproxy
    externalUrlSuffix: test.yourdomain.com

peer:
  name: peer0
  type: anchor
  address: peer0.carrier-net.test.yourdomain.com:443
  localMspId: carrierMSP
  logLevel: info
  tlsStatus: true
  channelName: AllChannel
  ordererAddress: orderer1.supplychain-net.test.yourdomain.com:443
