#helm install orderer1 -f values/proxy-and-vault/orderer.yaml -n supplychain-net fabric-orderernode
global:
  version: 2.5.4
  serviceAccountName: vault-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    address: http://vault.url:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    tls: false
  proxy:
    provider: haproxy
    externalUrlSuffix: test.yourdomain.com

certs:
  generateCertificates: true
  orgData:
    caAddress: ca.supplychain-net.test.yourdomain.com
    caAdminUser: supplychain-admin
    caAdminPassword: supplychain-adminpw
    orgName: supplychain
    type: orderer
    componentSubject: "O=Orderer,L=51.50/-0.13/London,C=GB"
  settings:
    #Flag to create configmaps for the organization. This flag must be set to true when installing the first orderer/peer in organization and false for others.
    createConfigMaps: true
    refreshCertValue: false
    addPeerValue: false
    removeCertsOnDelete: true
    removeOrdererTlsOnDelete: true

orderer:
  consensus: raft
  logLevel: info
  localMspId: supplychainMSP
  tlsstatus: true
