##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
# appVersion: "2.0"
description: "Quorum: This Helm Chart generates the crypto material for raft consensus only if they are not already available in the vault."
name: quorum-raft-crypto-gen
version: '0.15.0'
appVersion: latest
keywords:
  - bevel
  - ethereum
  - quorum
  - hyperledger
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
