# Store trustee's name if it is not already set
- name: "Store trustee's name"
  set_fact:
    trustee_name: "{{ org.services.trustee | default('') }}"
  when: trustee_name == ''

# Store endorser's name if it is not already set
- name: "Store endorser's name"
  set_fact:
    endorser_name: "{{ org.services.endorser | default('') }}"
  when: endorser_name == ''

# Add each steward's details (name, public IP, node port, client port) to the steward_list
- name: "Maintain each steward's node info"
  set_fact:
    steward_list: "{{ steward_list + [{'name': stewards_item.name, 'publicIp': stewards_item.publicIp, 'nodePort': stewards_item.node.ambassador, 'clientPort': stewards_item.client.ambassador}] }}"
  loop: "{{ stewards }}"
  loop_control:
    loop_var: stewards_item
  ignore_errors: true
