apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: m-generate-ambassador-certs-job
  namespace: m-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: m-generate-ambassador-certs-job
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-tlscerts-gen
    sourceRef:
      kind: GitRepository
      name: flux-quodlt
      namespace: flux-quodlt
  values:
    global:
      vault:
        type: hashicorp
        address: http://dev-vault-public.dev.aws.blockchaincloudpoc-develop.com
        role: vault-role
        authPath: quodltm
        serviceAccountName: vault-auth
        secretPrefix: secretsv2/data/m
    name: "m"
    image:
      initContainerName: ghcr.io/hyperledger/bevel-alpine:latest
      certsContainerName: ghcr.io/hyperledger/bevel-build:jdk8-latest
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
    subjects:
      root_subject: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
      cert_subject: "CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB"
    opensslVars:
      domain_name: "m.sau99.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_api: "mapi.sau99.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_web: "mweb.sau99.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_tessera: "m-tessera.m-quo"
      clientPort: 8888
    settings:
      removeGenesisOnDelete: true
    label:
