dependencies:
  - name: bevel-storageclass
    alias: storage
    repository: "file://../../../shared/charts/bevel-storageclass"
    tags:
      - storage
    version: ~1.0.0
  - name: fabric-catools
    alias: certs
    repository: "file://../fabric-catools"
    tags:
      - catools
    version: ~1.1.0
    condition: certs.generateCertificates
