##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

global:
  # HLF Network Version
  #Eg. version: 2.5.4
  version: 2.5.4
  #Provide the service account name which will be created.
  serviceAccountName: vault-auth
  cluster:
    provider: aws  # choose from: minikube | aws | azure | gcp
    cloudNativeServices: false # only 'false' is implemented
  vault:
    #Provide the type of vault
    #Eg. type: hashicorp
    type: hashicorp
    #Provide the vaultrole for an organization
    #Eg. vaultrole: org1-vault-role
    role: vault-role
    #Provide the vault server address
    #Eg. vaultaddress: http://Vault-884963190.eu-west-1.elb.amazonaws.com
    address:
    #Provide the kubernetes auth backed configured in vault for an organization
    #Eg. authpath: supplychain
    authPath: supplychain
    #Provide the secret engine.
    secretEngine: secretsv2
    #Provide the vault path where the secrets will be stored
    secretPrefix: "data/supplychain"
    #Kuberenetes secret for vault ca.cert
    #Enable or disable TLS for vault communication if value present or not
    #Eg. tls: vaultca
    tls: 

  proxy:
    #This will be the proxy/ingress provider. Can have values "none" or "haproxy"
    #Eg. provider: "haproxy"
    provider: "haproxy"
    #This field contains the external URL of the organization
    #Eg. externalUrlSuffix: test.blockchaincloudpoc.com
    externalUrlSuffix: test.blockchaincloudpoc.com

storage:
  #Provide storage size for Orderer Volume
  #Eg. size: 512Mi
  size: 512Mi
  # NOTE: when you set this to Retain, the volume WILL persist after the chart is delete and you need to manually delete it
  reclaimPolicy: "Delete" # choose from: Delete | Retain
  volumeBindingMode: Immediate # choose from: Immediate | WaitForFirstConsumer
  allowedTopologies:
    enabled: false

certs:
  # Flag indicating the creation of certificates.
  generateCertificates: true
  orgData:
    caAddress: ca.supplychain-net:7051
    caAdminUser: supplychain-admin
    caAdminPassword: supplychain-adminpw
    #Provide organization's name in lowercases
    #Eg. orgName: supplychain
    orgName: supplychain
    #Provide organization's type (orderer or peer)
    #Eg. type: orderer
    type: orderer
    #Provide organization's subject
    #Eg. componentSubject: "O=Orderer,L=51.50/-0.13/London,C=GB"
    componentSubject: "O=Orderer,L=51.50/-0.13/London,C=GB"

  settings:
    #Flag to create configmaps for the organization. This flag must be set to true when installing the first orderer/peer in organization and false for others.
    createConfigMaps: true
    refreshCertValue: false
    addPeerValue: false
    removeCertsOnDelete: false
    removeOrdererTlsOnDelete: false

image:
  #Provide the valid image repository for fabric orderer
  #Eg. orderer: hyperledger/fabric-orderer
  orderer: ghcr.io/hyperledger/bevel-fabric-orderer
  #Provide the valid image name and version to read certificates from vault server
  #Eg.alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
  alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
  #Provide the valid image name and version for healthCheck of kafka
  #Eg. healthCheck: busybox
  healthCheck: busybox
  #Provide the secret to use if private repository
  #Eg. pullSecret: regcred
  pullSecret: 

orderer:
  #Provide the name of the consensus. Currently support raft and kafka
  #Eg. consensus: raft
  consensus: raft
  #Provide the logLevel for orderer deployment
  #Eg. logLevel: info
  logLevel: info
  #Provide the localMspId for orderer deployment
  #Eg. localMspId: supplychainMSP
  localMspId: supplychainMSP
  #Provide the value for tlsStatus to be true or false for orderer deployment
  #Eg. tlsStatus: true
  tlsStatus: true
  #Provide the interval in which the orderer to signal the connection has kept alive  
  #Eg. keepAliveServerInterval: 10s
  keepAliveServerInterval: 10s
  #Provide the serviceType a peer
  #Eg. serviceType: NodePort
  serviceType: ClusterIP
  ports:
    grpc:
      #Provide a nodeport for orderer in the range of 30000-32767 (optional)
      #Eg. nodeport: 30001
      nodeport: 
      #Provide a cluster IP port for orderer to be exposed.
      #Eg. clusterIpPort: 7050
      clusterIpPort: 7050
    metrics:
      enabled: false
      clusterIpPort: 9443
  resources:
    limits:
      # Provide the limit memory for node
      # Eg. memory: 512M
      memory: 512M
      # Provide the limit cpu for node
      # Eg. cpu: 1
      cpu: 1
    requests:
      # Provide the requests memory for node
      # Eg. memory: 512M
      memory: 512M
      # Provide the requests cpu for node
      # Eg. cpu: 0.25
      cpu: 0.25

kafka:
  #Provide the interval in seconds you want to iterate till all  kafka services to be ready
  #Eg. readinessCheckInterval: 5
  readinessCheckInterval: 5
  #Provide the threshold till you want to check if all specified kafka brokers are up and running
  #Eg. readinessThresHold: 4
  readinessThresHold: 4
  #Provide the kafka broker list
  #Eg. brokers:
  #      - kafka-0.broker.org1-net.svc.cluster.local:9092
  #      - kafka-1.broker.org1-net.svc.cluster.local:9092
  #      - kafka-2.broker.org1-net.svc.cluster.local:9092
  #      - kafka-3.broker.org1-net.svc.cluster.local:9092
  brokers:

healthCheck: 
  # The amount of times to retry fetching from/writing to Vault before giving up.
  # Eg. retries: 10
  retries: 10
  # The amount of time in seconds to wait after an error occurs when fetching from/writing to Vault.
  # Eg. sleepTimeAfterError: 15  
  sleepTimeAfterError: 15

labels:
  service: []
  pvc: []
  deployment: []
