##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
apiVersion: v1
name: besu-node
description: Hyperledger Besu nodes for a POA network
<<<<<<< HEAD
<<<<<<< HEAD
version: 0.15.2
=======
version: 1.0.0
>>>>>>> upstream/develop
=======
version: 1.0.1
>>>>>>> upstream/develop
appVersion: latest
keywords:
  - bevel
  - ethereum
  - besu
  - hyperledger
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
