
- name: Deploy Stewards
  include_role:
    name: create/helm_component/new-generate-keys
  vars:
    node_public_ip: "{{ steward.publicIp }}"
    node_port: "{{ steward.node.port | int }}"
    node_external_port: "{{ steward.node.ambassador | int }}"
    client_public_ip: "{{ steward.publicIp }}"
    client_port: "{{ steward.client.port | int }}"
    client_external_port: "{{ steward.client.ambassador | int }}"
    component_name: "{{ steward.name | lower }}"

# Push the created deployment files to repository
- name: "Push the created deployment files to repository"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    msg: "[ci skip] Pushing key management job files for {{ component_ns }}"
    gitops: "{{ org.gitops }}"

# Check if all stewards are running
- name: Check if all stewards are running
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: Pod
    component_name: "{{ steward.name | lower }}"
    label_selectors:
      - app = "{{ steward.name | lower }}"
    namespace: "{{ component_ns }}"
