##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# The following are for overriding global values
global:
  #Provide the service account name which will be created.
  #Eg. serviceAccountName: vault-auth
  serviceAccountName: vault-auth
  vault:
    #Provide the type of vault
    #Eg. type: hashicorp
    type: hashicorp
    #Provide the vault role used.
    #Eg. role: vault-role
    role: vault-role
    #Provide the vault server address
    #Eg. address: http://54.226.163.39:8200
    address:
    #Provide the vault authPath configured to be used.
    #Eg. authPath: supplychain
    authPath: supplychain
    #Provide the network type
    network: corda
    #Provide the secret engine.
    #Eg. secretEngine: secretsv2
    secretEngine: secretsv2
    #Provide the vault path where the tls certificates will be stored
    #Eg. secretPrefix: data/warehouse-bes/crypto/warehouse/tls MUST use data/
    secretPrefix: "data/supplychain"
  proxy:
    # Provide external URL for cert generation
    externalUrlSuffix: test.blockchaincloudpoc.com

# Provide information regarding the Docker images used.
image:
  #Provide the image repository for all containers
  #Eg. repository: ghcr.io/hyperledger/bevel-alpine
  repository: ghcr.io/hyperledger/bevel-alpine
  tag: latest
  # Provide the docker-registry secret created and stored in kubernetes cluster as a secret.
  # Eg. imagePullSecret: regcred
  pullSecret: 
  # Pull policy to be used for the Docker image
  # Eg. pullPolicy: Always
  pullPolicy: IfNotPresent

# Settings for certificate generation
settings:
  #Set value to true when using network_services like doorman and nms
  #Eg. networkServices: true
  networkServices: true # false 
