---
#helm install member-2 -f values/noproxy-and-novault/txnode-sec.yml -n carrier-bes besu-node
global:
  serviceAccountName: vault-auth
  cluster:
    provider: azure # choose from: minikube | aws | azure | gcp
    cloudNativeServices: false
    #Provide the kubernetes host url
    #Eg. kubernetesUrl: https://10.3.8.5:8443
    kubernetesUrl: "https://kubernetes.url"
  vault:
    type: hashicorp
    #Provide the vault role used.
    role: vault-role
    #Provide the network type
    network: indy
    #Provide the vault server address
    address: "http://vault.url:8200"
    #Provide the vault authPath configured to be used.
    authPath: university
    #Provide the secret engine.
    secretEngine: secretsv2
    #Provide the vault path where the secrets will be stored
    secretPrefix: "data/university"
  proxy:
    provider: ambassador

settings:
  removeKeysOnDelete: true
  identities:
    trustee: 
    endorser: university-endorser
    stewards: 
    - university-steward-1
    - university-steward-2
    - university-steward-3
    - university-steward-4
