##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Default values for Certs Generator chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

---
global:
  #############################################################
  #               HashiCorp Vault Configuration               #
  #############################################################
  # NOTE: Make sure that the vault is already unsealed, intialized and configured to
  # use Kubernetes service account token based authentication.
  # For more info, see https://www.vaultproject.io/docs/auth/kubernetes
  vault:
    # Type of Vault to support other providers. Currently, only `hashicorp` and `kubernetes` is supported
    type: hashicorp
    # URL of the Vault server
    # Eg. address: http://vault.example.com:8200
    address:
    # Role used for authentication with Vault
    role: vault-role
    # Authentication path for Vault
    authPath: quorumNode
    # Serviceaccount name that will be created for Vault Auth and k8S Secret management
    # NOTE: Make sure that the service account is already created and autheticated to use the vault.
    serviceAccountName: vault-auth
    # The value for vault secret prefix which must start with `data/`
    secretPrefix: data/quorumNode

#############################################################
#                   Basic Configuration                     #
#############################################################

# Provide the name of the node
# Eg. name:
name: node_1

# Provide information regarding the Docker images used.
image:
  # Provide the alpine utils image, which is used for all init-containers of deployments/jobs.
  # NOTE: The alpine image used is the base alpine image with CURL installed.
  # Eg. initContainerName: ghcr.io/hyperledger/bevel-alpine:latest
  initContainerName: ghcr.io/hyperledger/bevel-alpine:latest
  # Provide the image for the certs container.
  # Eg. certsContainerName: ghcr.io/hyperledger/bevel-build:jdk8-latest
  certsContainerName: ghcr.io/hyperledger/bevel-build:jdk8-latest
  # Docker-registry secret stored in kubernetes cluster as a secret
  # Eg. imagePullSecret: regcred
  imagePullSecret: regcred
  # Pull policy to be used for the Docker image
  # Eg. pullPolicy: Always
  pullPolicy: IfNotPresent

#############################################################
#                  SUBJECT Details                          #
#############################################################
# This section details the X509 subjects

subjects:
  # Mention the subject for rootca
  # Eg. rootca: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
  root_subject: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
  # Mention the subject for cert
  # Eg. cert_subject: "CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB"
  cert_subject: "CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB"

#############################################################
#                  Opensslvars Details                      #
#############################################################
# This section details of the Openssl used in domain creation

opensslVars:
  # Provides the domain name
  # Eg. domain_name: nodename.rc.dev2.aws.example.com
  domain_name:
  # Domain name for api endpoint
  # Eg. domain_name_api: nodenameapi.rc.dev2.aws.example.com
  domain_name_api:
  # Domain name for web endpoint 
  # Eg. domain_name_web: nodenameweb.rc.dev2.aws.example.com
  domain_name_web:
  # Domain name for tessera endpoint
  # Eg. domain_name_tessera: nodename-tessera.nodename-quo
  domain_name_tessera:
  # Transaction manager client port
  clientport: 8888

settings:
  removeGenesisOnDelete: true
