##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
appVersion: "latest"
description: "Shared: Deploys a StorageClass that can be used to provision persistent volumes for nodes."
name: bevel-storageclass
<<<<<<< HEAD
version: '0.15.1'
=======
version: 1.0.0
>>>>>>> upstream/develop
