##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Primary genesis setup
- name: "Primary genesis setup"
  include_tasks: primary_genesis.yaml

# Secondary genesis setup if there are multiple organizations
- name: "Secondary genesis Setup"
  include_tasks: secondary_genesis.yaml
  when: network['organizations'] | length > 1
