# helm install genesis -f values/proxy-and-vault/genesis.yaml -n supplychain-quo --create-namespace goquorum-genesis
global:
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
    kubernetesUrl: https://kubernetes.url
  vault:
    type: hashicorp
    role: vault-role
    network: quorum
    address: http://vault.demo.com:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
settings:
  removeGenesisOnDelete: true
