# helm install genesis -f values/proxy-and-vault/genesis-sec.yaml -n carrier-quo goquorum-genesis
global:
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
    kubernetesUrl: https://kubernetes.url
  vault:
    type: hashicorp
    network: quorum
    address: http://vault.demo.com:8200
    authPath: supplychain
    secretEngine: secretsv2
    secretPrefix: "data/supplychain"
    role: vault-role
settings:
  removeGenesisOnDelete: true
  secondaryGenesis: true
