---
#helm install member-2 -f values/proxy-and-vault/txnode-sec.yml -n carrier-bes --set global.proxy.p2p=15016 besu-node
global:
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
    kubernetesUrl: https://300125A3D09FFA0A178EC3522C96BBB8.gr7.eu-west-1.eks.amazonaws.com # if Proxy and Vault else keep it empty # https://kubernetes.url
  vault:
    type: hashicorp
    network: quorum
    address: http://vault.vault.svc.cluster.local:80 # http://vault.demo.com:8200
    authPath: genesis
    secretEngine: secretsv2
    secretPrefix: "data/genesis"
    role: vault-role
  proxy:
    provider: ambassador
    externalUrlSuffix: sau99.dev.aws.blockchaincloudpoc-develop.com # test.yourdomain.com
    tmport: 443

storage:
  size: "2Gi"

tessera:
  enabled: true
  tessera:
    port: 443
    peerNodes: 
      - url: "https://supplychain.test.yourdomain.com"
    resources:
      cpuLimit: 0.25
      cpuRequest: 0.05
      memLimit: "2G"
      memRequest: "1G"
    password: 'password'
  storage:
    enabled: false
    size: 1Gi
    dbSize: 2Gi
    allowedTopologies:
      enabled: false
  
tls:
  enabled: true
  settings:
    certSubject: CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB
    tmTls: true

node:
  goquorum:
    metrics:
      serviceMonitorEnabled: true
    resources:
      cpuLimit: 0.25
      cpuRequest: 0.05
      memLimit: "1G"
      memRequest: "300M"
    account:
      password: 'password'
    p2p:
      discovery: false
