---
# helm install validator-1 -f values/proxy-and-vault/validator.yml -n supplychain-quo --set global.proxy.p2p=15011 quo-node
# helm upgrade validator-1 -f values/proxy-and-vault/validator.yml -n supplychain-quo --set global.proxy.p2p=15011 quo-node
global:
  serviceAccountName: vault-auth
  cluster:
    provider: aws
    cloudNativeServices: false
  vault:
    type: hashicorp
    role: vault-role
    network: quorum
    address: http://dev-vault-public.dev.aws.blockchaincloudpoc-develop.com # http://vault.demo.com:8200
    authPath: genesis
    secretEngine: secretsv2
    secretPrefix: "data/genesis"
  proxy:
    provider: ambassador
    externalUrlSuffix: sau99.dev.aws.blockchaincloudpoc-develop.com # test.yourdomain.com
