##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

apiVersion: v1
description: "Quorum: This Helm chart generates certificates and keys required by Tessera transaction manager."
name: quorum-tessera-key-mgmt
appVersion: latest
keywords:
  - bevel
  - ethereum
  - quorum
  - hyperledger
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
version: 1.0.0
