{{- if .Values.peer.ports.metrics.enabled }}
{{- if $.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name}}
    app.kubernetes.io/component: fabric
    app.kubernetes.io/part-of: {{ include "fabric-orderernode.fullname" . }}
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}
  namespace:  {{ .Release.Namespace }}
spec:
  jobLabel: {{ .Release.Name }}
  endpoints:
    - honorLabels: true
      port: operations
  namespaceSelector:
    matchNames:
      -  {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }} 
      run: {{ .Release.Name }}
{{- end }} 
{{- end }} 
