apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dscp-ipfs.fullname" . }}-config
  labels:
    {{- include "dscp-ipfs.labels" . | nindent 4 }}
data:
  healthCheckPollPeriod: {{ .Values.config.healthCheckPollPeriod | quote }}
  healthCheckTimeout: {{ .Values.config.healthCheckTimeout | quote }}
  healthCheckPort: {{ .Values.config.healthCheckPort | quote }}
  logLevel: {{ .Values.config.logLevel }}
  nodeHost: {{ .Release.Name }}
  ipfsCommand: {{ .Values.config.ipfsCommand }}
  ipfsLogLevel: {{ .Values.config.ipfsLogLevel }}
  ipfsArgs: {{ .Values.config.ipfsArgs | toJson | quote }}
  ipfsSwarmAddrFilters: {{ .Values.config.c | toJson | quote }}
  {{- if .Values.config.ipfsBootNodeAddress }}
  ipfsBootNodeAddress: {{ .Values.config.ipfsBootNodeAddress }}
  {{- end }}
  ipfsApiPort: {{ include "dscp-ipfs.ipfsApiPort" . }}
  ipfsSwarmPort: {{ .Values.config.ipfsSwarmPort | quote }}
  dataVolumeSize: {{ .Values.storage.dataVolumeSize | quote }}
