apiVersion: v1
kind: Secret
metadata:
  name: "substrate-node-{{ include "dscp-ipfs.fullname" . }}-keys"
  labels:
    {{- include "dscp-ipfs.labels" . | nindent 4 }}
{{- if and .Values.config.publicKey .Values.config.privateKey }}
data:
  publicKey: {{ .Values.config.publicKey | b64enc | quote }}
  privateKey: {{ .Values.config.privateKey | b64enc | quote }}
{{- else }}
data: {}
{{- end }}
