apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mmquorum
  namespace: m-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: mmquorum
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-member-node
    sourceRef:
      kind: GitRepository
      name: flux-quodlt
      namespace: flux-quodlt
  values:
    nameOverride: m
    replicaCount: 1
    global:
      vault:
        type: hashicorp
        address: http://dev-vault-public.dev.aws.blockchaincloudpoc-develop.com
        secretPrefix: secretsv2/data/m/crypto/m
        serviceAccountName: vault-auth
        keyName: quorum
        tm_keyName: tm
        role: vault-role
        authPath: quodltm
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: ghcr.io/hyperledger/bevel-alpine:latest
    node:
      name: m
      status: default
      consensus: ibft
      subject: O=m,OU=m,L=47.38/8.54/Zurich,C=CH
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keyStore: keystore_1
      serviceType: ClusterIP
      lock: false
      ports:
        rpc: 8546
        quorum: 21000

    tm:
      type: tessera
      
    tessera:
      url: "https://m.sau99.dev.aws.blockchaincloudpoc-develop.com:443"
      clientUrl: "http://m-tessera:8888" #TODO: Enable tls strict for q2t
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjViNzNlNGIiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg2ZmVhOTQzMDNiMWYzMmU5NGJmMGVhMzhmN2YxYjIzOTU0ZmMzZWZjMjY1ODRjOTRmNDA1MmQxNDg4NjU1YWIyY2MxZjM0NmJiY2JmYzU4YTY4NTM0NTA0Yjg0MTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDBjMCIsCiAgImdhc0xpbWl0IjogIjB4ZTAwMDAwMDAiLAogICJkaWZmaWN1bHR5IjogIjB4MSIsCiAgIm1peEhhc2giOiAiMHg2Mzc0Njk2MzYxNmMyMDYyNzk3YTYxNmU3NDY5NmU2NTIwNjY2MTc1NmM3NDIwNzQ2ZjZjNjU3MjYxNmU2MzY1IiwKICAiY29pbmJhc2UiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAiYWxsb2MiOiB7CiAgICAiMzAzYjFmMzJlOTRiZjBlYTM4ZjdmMWIyMzk1NGZjM2VmYzI2NTg0YyI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgImY0MDUyZDE0ODg2NTVhYjJjYzFmMzQ2YmJjYmZjNThhNjg1MzQ1MDQiOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfQogIH0sCiAgIm51bWJlciI6ICIweDAiLAogICJnYXNVc2VkIjogIjB4MCIsCiAgInBhcmVudEhhc2giOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgp9
    staticNodes:
      [
    "enode://96baeb697042b8151bff1e3e53b9e591ae2c9763919cbff27183d17fb35492b6a462f786ef4df12e6df05fb9e6d030eae6c9724f139b41c1b2390cb74e23313d@c.sau99.dev.aws.blockchaincloudpoc-develop.com:15010?discport=0",
    "enode://e275083f37ae28ca37e73609fb7fe2db55bdb9fa7165a66d327211f1bda0541e521fb87824621e0740cfc10bfbe9c60add04e8a1f3176e11c150c539cc436b8b@v1.sau99.dev.aws.blockchaincloudpoc-develop.com:15014?discport=0",
    "enode://02ae10bb92aeb40b758381b3b572f08ad50f60beb8aa0ed86fec6e4f37449a419c934f83c7852a4086604c05334f122b7d33c6388442ff625574dda69832c1ad@m.sau99.dev.aws.blockchaincloudpoc-develop.com:15020?discport=0",
    "enode://13a6751134b0d2b0950e72b766c70cd8e60a93dd6a775fc9eb132b505d9bd37ae76c96c2569d36990e4340eaf10c55df82d5d832e2e7adced991f29a13231598@v2.sau99.dev.aws.blockchaincloudpoc-develop.com:15024?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: sau99.dev.aws.blockchaincloudpoc-develop.com
      quorumPort: 15020
    storage:
      storageClassName: m-bevel-storageclass
      storageSize: 1Gi
      dbStorage: 1Gi # NUA

    labels:

    settings:
      removeGenesisOnDelete: true
