##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

---
nameOverride: ""

# Number of replicas for pods
replicaCount: 1

# The following are for overriding global values
global:
  vault:
    # Type of Vault to support other providers. Currently, only `hashicorp` and `kubernetes` is supported.
    type: hashicorp
    # URL of the Vault server
    address: ""
    # The value for vault secret prefix which must start with `data/`
    secretprefix: data/node
    # Serviceaccount name that will be created for Vault Auth and k8S Secret management
    serviceAccountName: vault-auth
    # key name from where quorum secrets will be read
    keyName: quorum
    # key name from where transaction-manager secrets will be read
    tm_keyName: tm
    # Role used for authentication with Vault
    role: vault-role
    # Authentication path for Vault
    authPath: node

#These are the various docker images being used by this chart. update them as needed
images:
  # Valid image name and version for quorum node
  node: quorumengineering/quorum:2.1.1
  # Valid image name and version to read certificates from vault server
  alpineutils: ghcr.io/hyperledger/bevel-alpine:latest

node:
  # Name for Quorum node
  name: node
  # Status of the node as default, additional
  status: default
  # Id which is obtained when the new peer is added for raft consensus
  # This field is only for RAFT consensus and only when a new node is added to existing network
  peer_id: 5
  # Consesus for the Quorum network, values can be 'raft' or 'ibft'
  consensus: ibft
  # mountpath for Quorum pod
  #Eg. mountPath: /etc/quorum/qdata
  mountPath: /etc/quorum/qdata
  # K8s secret name in the namespace
  imagePullSecret: regcred
  # keystore file name
  keystore: keystore_1
  # k8s service type
  servicetype: ClusterIP
  lock: false
  # Container and service ports
  ports:
    rpc: 8546
    raft: 50401
    quorum: 21000

tm:
  type: none

tessera:
  # Tessera node's own url. This should be local. Use http if tls is OFF
  url: 
  clienturl: 

# genesis.json file in base64 format
# Eg. genesis: ewogICAgImFsbG9jIjogewogICAgICAgICIwOTg2Nzk2ZjM0ZDhmMWNkMmI0N2M3MzQ2YTUwYmY2
#     OWFhOWM1NzcyIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAw
#     MDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgImY2MjkyNTQ1YWVjNTkyMDU4MzQ
genesis:
      
# Staticnodes as an array
# Eg. staticnodes: 
#  - enode://293ce022bf114b14520ad97349a1990180973885cc2afb6f4196b490397e164fabc87900736e4b685c5f4cf31479021ba0d589e58bd0ea6792ebbfd5eb0348af@node1.quo.demo.aws.blockchaincloudpoc.com:15011?discport=0&raftport=15012
#  - enode://4e7a1a15ef6a9bbf30f8b2a6b927f4941c9e80aeeeed14cfeeea619f93256b41ef9994b9a8af371f394c2a6de9bc6930e142c0350399a22081c518ab2d27f92a@node2.quo.demo.aws.blockchaincloudpoc.com:15021?discport=0&raftport=15022
#  - enode://947fa59385da72f4a68b7348ef5dab7e759148b48b30892c29b7b03a872233a6475a13fd5df62ea75abff9981d459606c1f878cd6ab929307eac6b56b19424bd@node3.quo.demo.aws.blockchaincloudpoc.com:15031?discport=0&raftport=15032
#  - enode://b28ac5bd1c554d05d68db65b0c3351838249e5b935e04d4b361745b74e6c7b3379927eefc11a5fef605fa64d14d000645e182662c51f5bf4a9dd228377f0e1ba@node4.quo.demo.aws.blockchaincloudpoc.com:15041?discport=0&raftport=15042
staticNodes:

proxy:
  # This will be the proxy/ingress provider. Can have values "ambassador" or "haproxy"
  # TODO "haproxy" has not been tested
  #Eg. provider: "ambassador"
  provider: "ambassador"
  # This field contains the external URL of the node
  external_url: 
  # Following are the ports that are exposed externally via the proxy
  quorumPort: 15031  
  portRaft: 15032

storage:
  # Kubernetes storageclass for node
  storageClassName: bevelStorageClass
  # Memory for node
  storageSize: 1Gi
  # Memory for database
  dbStorage: 1Gi

settings:
  removeGenesisOnDelete: true