##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
# helm install validator-1 -f values/noproxy-and-novault/node.yaml -n supplychain-subs substrate-node
# helm upgrade validator-1 -f values/noproxy-and-novault/node.yaml -n supplychain-subs substrate-node

global:
  serviceAccountName: vault-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: kubernetes # hashicorp | kubernetes

image:
  repository: ghcr.io/inteli-poc/dscp-node
  tag: v4.3.1
  pullPolicy: IfNotPresent

initContainer:
  image:
    repository: crazymax/7zip
    tag: latest

kubectl:
  image:
    repository: bitnami/kubectl
    tag: latest

googleCloudSdk:
  image:
    repository: google/cloud-sdk
    tag: slim

serviceAccount:
  create: false
  name: vault-auth

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

ingress:
  enabled: false

node:
  chain: inteli
  command: ./dscp-node
  isBootnode:
    enabled: true # false | true
    bootnodeName: validator-1
    bootnodeAddr: validator-1-substrate-node-0-rc-p2p.supplychain-subs
    bootnodePort: 8080

  dataVolumeSize: 10Gi
  replicas: 1
  role: validator # full | validator
  customChainspecUrl: true
  chainDataSnapshotUrl: false
  customChainspecPath: "/data/chainspec.json"
  chainDataGcsBucketUrl: false
  collator:
    isParachain: false
    relayChainDataSnapshotUrl: false
    relayChainDataGcsBucketUrl: false
    
  enableStartupProbe: false
  enableReadinessProbe: false
  flags:
    - "--rpc-external"
    - "--ws-external"
    - "--rpc-methods=Unsafe"
    - "--rpc-cors=all"
    - "--unsafe-ws-external"
    - "--unsafe-rpc-external"
  persistGeneratedNodeKey: false
  
  resources: {}
  serviceMonitor:
    enabled: false
    
  perNodeServices:
    createApiService: true
    createP2pService: true
    p2pServiceType: ClusterIP
    setPublicAddressToExternal:
      enabled: false
      ipRetrievalServiceUrl: https://ifconfig.io
  podManagementPolicy: Parallel
  
  ports:
    p2p: 8080
    ws: 9944
    rpc: 9933
    
  tracing:
    enabled: false
      
  substrateApiSidecar:
    enabled: false
