##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
# helm install validator-1 -f values/noproxy-and-novault/node.yaml -n supplychain-subs substrate-node
# helm upgrade validator-1 -f values/noproxy-and-novault/node.yaml -n supplychain-subs substrate-node

global:
  serviceAccountName: vault-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: kubernetes # hashicorp | kubernetes

node:
  isBootnode:
    enabled: true # false | true
    bootnodeName: validator-1
    bootnodeAddr: validator-1-substrate-node-0-rc-p2p.supplychain-subs
    bootnodePort: 8080
    role: validator # full | validator
  diffNamespace: 
    enabled: true
    auraSecretPhraseKey: "mirror accident garden style such museum universe sweet disagree smile wing theme"
    granSecretPhraseKey: "keen tower comic coast pond hub garage beyond vapor word tissue shove"
    nodeKey: ec4bc694bea8a9fa798a4e53a76784b0ee78434ccadf892b35b1720cb83d9f05
    bootnodeId: 12D3KooWByHfabLDGdDzUYx8QTiL9Kk8ejA3UHNdbktQefP2NFdz
genesisNamespace: supplychain-subs # New
