##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
# helm install validator-1 -f values/noproxy-and-novault/node.yaml -n supplychain-subs substrate-node
# helm upgrade validator-1 -f values/noproxy-and-novault/node.yaml -n supplychain-subs substrate-node

global:
  serviceAccountName: vault-auth
  cluster:
    provider: azure
    cloudNativeServices: false
  vault:
    type: kubernetes # hashicorp | kubernetes

node:
  isBootnode:
    enabled: true # false | true
    bootnodeName: validator-1
    bootnodeAddr: validator-1-substrate-node-0-rc-p2p.supplychain-subs
    bootnodePort: 8080 # 30333
    role: validator # full | validator
