# Deploy Steward nodes
- name: "Deploy Steward nodes"
  include_tasks: nested.yaml
  loop: "{{ org.services.stewards }}"
  loop_control:
    loop_var: steward
  when: steward is defined and steward | length > 0
