##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Deploy Steward's node
- name: "Deploy {{ steward.name }} node in the {{ org.name }} organization"
  include_role:
    name: create/helm_component/peer
  vars:
    node_public_ip: "{{ steward.publicIp }}"
    node_port: "{{ steward.node.port | int }}"
    node_external_port: "{{ steward.node.ambassador | int }}"
    client_public_ip: "{{ steward.publicIp }}"
    client_port: "{{ steward.client.port | int }}"
    client_external_port: "{{ steward.client.ambassador | int }}"
    component_name: "{{ steward.name | lower }}"

# Push the created deployment files to repository
- name: "Push the created deployment files to repository"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/git_push"
  vars:
    GIT_DIR: "{{ playbook_dir }}/../../../"
    msg: "[ci skip] Pushing key management job files for {{ component_ns }}"
    gitops: "{{ org.gitops }}"

# Check if Steward's node is running
- name: "Check if {{ steward.name }} node is running in the {{ org.name }} organization"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/helm_component"
  vars:
    component_type: Pod
    component_name: "{{ steward.name | lower }}"
    label_selectors:
      - app = {{ component_name }}
    namespace: "{{ component_ns }}"
