##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

##################################################
# Playbook to cleanup platform specific resources
##################################################

- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
  # Cleanup all organizations' vault indy crypto
  - name: "Clean up Vault indy crypto"
    include_role:
      name: clean/vault
  
  # Clean up helpers directory
  - name: "Clean up helpers directory"
    include_role:
      name: clean/local_directories
