##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

#########################
# Playbook to create deployment files for namespaces, service account and clusterrolebinding
# Playbook arguments: complete network.yaml
#########################
- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
  # clean build directory
  - name: Remove build directory
    file:
      path: "./build"
      state: absent

  # # Validate input network.yaml
  # - name: "Validating network.yaml"
  #   include_role:
  #     name: check/validation

  # # Create namespaces for organizations
  # - name: 'Create namespace'
  #   include_role:
  #     name: create/namespace
  #   vars:
  #     component_name: "{{ organizationItem.name | lower }}-ns"
  #     component_type_name: "{{ organizationItem.type | lower }}"
  #     kubernetes: "{{ organizationItem.k8s }}"
  #     release_dir: "{{playbook_dir}}/../../../{{organizationItem.gitops.release_dir}}/{{ organizationItem.name | lower }}"
  #   loop: "{{ network['organizations'] }}"
  #   loop_control:
  #     loop_var: organizationItem

  - name: generate-keys
    include_role:
      name: create/helm_component/new-generate-keys
    vars:
      org_name: "{{ org.name | lower }}"
      stewards: "{{ org.services.stewards }}"
      cloud_provider: "{{ org.cloud_provider | lower }}"
      vault: "{{ org.vault }}"
      kubernetes: "{{ org.k8s }}"
      component_type: "generate_keys"
      component_ns: "{{ org_name }}-indy"
      component_name: "{{ org_name }}-generate-keys"
      values_dir: "{{playbook_dir}}/../../../{{org.gitops.release_dir}}"
      charts_dir: "{{ org.gitops.chart_source }}"
    loop: "{{ network['organizations'] }}"
    loop_control:
      loop_var: org

  # These variables can be overriden from the command line
  vars: 
    install_os: "linux"                           # Default to linux OS
    install_arch:  "amd64"                        # Default to amd64 architecture
    bin_install_dir:  "~/bin"                     # Default to /bin install directory for binaries
    add_new_org: false                            # Default to false when not defined.
    add_new_org_network_trustee_present: true     # Default to true when not defined.
    add_new_org_new_nyms_on_ledger_present: true  # Default to true when not defined.
