- name: Initialize variable and list
  set_fact:
    trustee_name: "{{ org.services.trustee | default('') }}"
    endorser_name: "{{ org.services.endorser | default('') }}"
    steward_list: []

# Generate IPFS node HelmRelease files
- name: "Maintain stewards"
  set_fact:
    steward_list: "{{ steward_list + [stewards_item.name] }}"
  loop: "{{ stewards }}"
  loop_control:
    loop_var: stewards_item
  ignore_errors: true

- name: Display initialized variables and list
  debug:
    msg: |
      trustee_name: "{{ trustee_name }}"
      endorser_name: "{{ endorser_name }}"
      steward_list: "{{ steward_list }}"

# Get the kubernetes server url
- name: Get the kubernetes server url
  shell: |
    KUBECONFIG={{ kubernetes.config_file }} kubectl config view --minify | grep server | cut -f 2- -d ":" | tr -d " "
  register: kubernetes_server_url

- name: "Ensure {{ values_dir }}/{{ org_name }} dir exists"
  include_role:
    name: "{{ playbook_dir }}/../../shared/configuration/roles/check/directory"
  vars:
    path: "{{ values_dir }}/{{ org_name }}"
    # path: "/home/saurabh/S-bevel/platforms/hyperledger-indy/releases/dev/saurabh"

# Generate Indy vault policy and role for stewards
- name: Stewards vault policy and role generating
  template:
    src: "{{ dlt_templates[component_type] }}"
    dest: "{{ values_dir }}/{{ org_name }}/{{ component_type }}.yaml"
  vars:
    kubernetes_server: "{{ kubernetes_server_url.stdout }}"
