apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mq-generate-ambassador-certs-job
  namespace: mq-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: mq-generate-ambassador-certs-job
  interval: 1m
  chart:
   spec:
    chart: platforms/quorum/charts/quorum-tlscerts-gen
    sourceRef:
      kind: GitRepository
      name: flux-quo-nw
      namespace: flux-quo-nw
  values:
    name: "mq"
    metadata:
      namespace: mq-quo
    image:
      initContainerName: ghcr.io/hyperledger/bevel-alpine:latest
      certsContainerName: ghcr.io/hyperledger/bevel-build:jdk8-latest
      imagePullSecret: regcred
      pullPolicy: IfNotPresent
    vault:
      address: http://dev-vault-public.dev.aws.blockchaincloudpoc-develop.com
      role: vault-role
      authpath: quo-nwmq
      serviceaccountname: vault-auth
      certsecretprefix: secretsv2/data/mq
      retries: 30
      type: hashicorp
    subjects:
      root_subject: "CN=DLT Root CA,OU=DLT,O=DLT,L=London,C=GB"
      cert_subject: "CN=DLT Root CA/OU=DLT/O=DLT/L=London/C=GB"
    opensslVars:
      domain_name: "mq.sau99.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_api: "mqapi.sau99.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_web: "mqweb.sau99.dev.aws.blockchaincloudpoc-develop.com"
      domain_name_tessera: "mq-tessera.mq-quo"
      clientport: 8888
