# Initialize variables for trustee
- name: "Initialize variables for trustee "
  set_fact:
    trustee_name: ""

# Set trusteevariables
- name: "Set trustee variables"
  set_fact:
    trustee_name: "{{ trustee_name | default('') if trustee_name != '' else (org.services.trustee | lower if org.services.trustee is defined else trustee_name) }}"
  loop: "{{ network['organizations'] }}"
  loop_control:
    loop_var: org

- name: Cleanup Vault indy crypto
  include_tasks: nested.yaml
  vars:
    org_name: "{{ org.name | lower }}"
    org_ns: "{{ org_name }}-indy"
    services: "{{ org.services }}"
    vault: "{{ org.vault }}"
  loop: "{{ network['organizations'] }}"
  loop_control:
    loop_var: org

- name: Pause for 2 minutes - VAULT DONE
  pause:
    minutes: 2
