apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authority-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-dtg
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-domain-genesis
    sourceRef:
      kind: GitRepository
      name: flux-main-indy
      namespace: flux-main-indy
  values:
    metadata:
      name: authority-dtg
      namespace: authority-ns
    organization:
      name: authority
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"L94EqViWpWvMejCXFggaB7","role":"0","verkey":"BS246WNpbFGwF2VM2YxjsquttrJ4eVQpELBjRTCrEs9a"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-trustee","dest":"6ige8fUWmH8utePiY7S4Jq","role":"0","verkey":"47nAjStmbbBMz9ZFWZwwYgdi9w3ajrbe6hU4ZLwTLNLv"},"metadata":{"from":"L94EqViWpWvMejCXFggaB7"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-1","dest":"D2M3pQJs26FRLU8vkpizzi","role":"2","verkey":"7Z5UL9qExYA9KzMbtRbZi2L869F3w2ZMX4ph9zQfVAgQ"},"metadata":{"from":"6ige8fUWmH8utePiY7S4Jq"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-2","dest":"WfqVmdbt7BnLKsYBkyFdAC","role":"2","verkey":"HAv2KbByMKvLJBwANBCoegNwYz2JgbjhW2MhHvWCY5Ju"},"metadata":{"from":"6ige8fUWmH8utePiY7S4Jq"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-trustee","dest":"k67nXEx7HsUG2u9KMVa4w","role":"0","verkey":"QV71qgE3icNDz17LypZvHuNMBNppo9Jket3S1oexBqz"},"metadata":{"from":"L94EqViWpWvMejCXFggaB7"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-1","dest":"Cwy5YhyRpXaohuWTw58v1M","role":"2","verkey":"7Wh3qG2xaTLwxbnWVdraWj9U3kL3tG8WAYN9fRUigDdM"},"metadata":{"from":"k67nXEx7HsUG2u9KMVa4w"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-2","dest":"CVS4iA2YkCibSZYzjjyE9E","role":"2","verkey":"7GEEZ1S6MLp4KDQjeXqce88TCuYCysdyZsB91U2197hy"},"metadata":{"from":"k67nXEx7HsUG2u9KMVa4w"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
