apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authority-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-dtg
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-domain-genesis
    sourceRef:
      kind: GitRepository
      name: flux-main-indy
      namespace: flux-main-indy
  values:
    metadata:
      name: authority-dtg
      namespace: authority-ns
    organization:
      name: authority
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"3zBxv8wZ5xVe1GaPmtsRCU","role":"0","verkey":"2dPr7mxFJYEfweqP6A6bvqmGU1zUqc6zdh7BqA3bTKUK"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-trustee","dest":"UgxZ2CuMp3fvghhh9kmVkx","role":"0","verkey":"G6JVXaZHveNvTxMER5dMtRuXMRo5qHFg9NYQQqVQad9Q"},"metadata":{"from":"3zBxv8wZ5xVe1GaPmtsRCU"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-1","dest":"EsgL9JPR1UPTeaaP66HC4m","role":"2","verkey":"8ZaTkWkXkb2NTLw6ff2T61Wbwcx8eaf84TZF7w1DfSZF"},"metadata":{"from":"UgxZ2CuMp3fvghhh9kmVkx"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-2","dest":"UtRPiHxnnvekhLWeRYMN3x","role":"2","verkey":"GCYrR3ZTnas639b8UZQFBsyZR8dYKnh5K5Zfu5juYc6N"},"metadata":{"from":"UgxZ2CuMp3fvghhh9kmVkx"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-trustee","dest":"DSaoAydh9bvDVEWnBfarpH","role":"0","verkey":"7nHenEHvmsSYjqcQ5wZdcbNvTSCEiVNiwrw8jHyEpuhf"},"metadata":{"from":"3zBxv8wZ5xVe1GaPmtsRCU"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-1","dest":"K1SCMDY6toe8QoT7eeXobb","role":"2","verkey":"ApFdaQmvQx1NnuVdxFDc1xzZncvoVud6gy1Fps6MF632"},"metadata":{"from":"DSaoAydh9bvDVEWnBfarpH"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-2","dest":"CwbwnpQK8dEkE59jJPqz72","role":"2","verkey":"7WVXkg3ZCMRUVKSSRQtuQF77mirXjGbfmichYfDdH7Ap"},"metadata":{"from":"DSaoAydh9bvDVEWnBfarpH"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
