apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authority-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-dtg
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-domain-genesis
    sourceRef:
      kind: GitRepository
      name: flux-main-indy
      namespace: flux-main-indy
  values:
    metadata:
      name: authority-dtg
      namespace: authority-ns
    organization:
      name: authority
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"WVAxzQ4d6w5T7JfvgDmqL","role":"0","verkey":"H56uM5JaCv3U9zsqbVrKzbB6grvQ9e5xxveFzNoYVPH"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-trustee","dest":"K7xTLQcpFTbmc78JpyfsP5","role":"0","verkey":"Asoo51Y8Uezoi5nMJkx8XYo9KsnfSkyxM6q54QhzCDBM"},"metadata":{"from":"WVAxzQ4d6w5T7JfvgDmqL"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-1","dest":"AzTH7mgN8SaKEd8QNH8RwG","role":"2","verkey":"6SpevGvQUPHfoggTYmJh3BAcyxEmzdKXXrAhiCu4Pnyj"},"metadata":{"from":"K7xTLQcpFTbmc78JpyfsP5"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-2","dest":"283LTJocPqrWLdd24QhZsN","role":"2","verkey":"cT3xcpzWFw96itWDTB85fENAptURMta13LH3LHZJvc9"},"metadata":{"from":"K7xTLQcpFTbmc78JpyfsP5"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-trustee","dest":"EqLexPtUfjH9ERziDSFyno","role":"0","verkey":"8YJWmy434JinhsUdyYT2BrpWe6ryPY5j7XjA4UE4r4QM"},"metadata":{"from":"WVAxzQ4d6w5T7JfvgDmqL"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-1","dest":"DNASDLZ9tafYs7Ey4dpepc","role":"2","verkey":"7jsvh7a8EwEecwTNZaG7FvDQWZPYiAD7QiM5gsCKwTKR"},"metadata":{"from":"EqLexPtUfjH9ERziDSFyno"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-2","dest":"41kaV5tohhvseKDcB6765j","role":"2","verkey":"2eFEaeFF7cBY5W5Arj83BGjHvnDHWecVooskv2SvhCwx"},"metadata":{"from":"EqLexPtUfjH9ERziDSFyno"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
