name: Hello World Pipeline

# Trigger the workflow on pushes to the "pipeline" branch
on:
  push:
    branches:
      - pipeline

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log Triggering User
        run: echo "Workflow triggered by user => ${{ github.actor }}"
      - name: Log Repository Owner
        run: echo "Workflow triggered by repository_owner => ${{ github.repository_owner }}"

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_IO_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_IO_USERNAME }}" --password-stdin

      # Extract the Git commit hash for versioning
      - name: Get Commit Hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Build Docker image with a dynamic tag
      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ secrets.GHCR_IO_USERNAME }}/frontend:${{ env.COMMIT_HASH }} ./frontend

      # Push Docker image with the dynamic tag
      - name: Push Docker Image
        run: docker push ghcr.io/${{ secrets.GHCR_IO_USERNAME }}/frontend:${{ env.COMMIT_HASH }}

      # Tag the image as 'latest' and push it to GHCR
      - name: Tag as Latest
        run: |
          docker tag ghcr.io/${{ secrets.GHCR_IO_USERNAME }}/frontend:${{ env.COMMIT_HASH }} ghcr.io/${{ secrets.GHCR_IO_USERNAME }}/frontend:latest
          docker push ghcr.io/${{ secrets.GHCR_IO_USERNAME }}/frontend:latest
